### ISSUE TITLE
Introduce yourself...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring23#1]
Hi everyone -

I wanted to start the semester with a post where everyone can reply with an introduction to themselves so we can get to know each other.

**Tell us what brought you to this course and any other details you care to share.**

About myself - I'm a web programmer and educator, living in Orange, MA. 

In addition to this course, I also teach [DGMD E-2](https://hesweb.dev/e2). In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. Independently, I do private consulting and share free web development guides and videos via https://codewithsusan.com.

More about my background here: [susanbuck.net](https://susanbuck.net/)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to working with you all this semester.

**Comment by ROK862** [comment]
Hello everyone, 

I'm Robbins, Sr. Software Engineer mainly concerned with the MERN stack. Well, until today?

I'm looking to explore other frameworks, perhaps as a way to broaden my skill set. I used to hate frameworks--still do, to be honest--but here we are. With this course, I want to get valuable inside and perhaps confirm my biased views about working with "other people's code." But who knows, maybe I might find valuable insights which I could use for some of my projects.

Either way, glad to be here! I'm looking forward to a productive semester.

**Comment by lmarshman** [comment]
Hello!

My name is Laura and I'm currently working on a programming certificate through HES. I've worked with a few frameworks in past HES courses, mainly Django and Flask. Until now, I've only worked with frameworks that use Python and would like to expand my knowledge of frameworks that use other langauges. 

I'm excited to dive in and learn more about Laravel/PHP!

**Comment by bar181** [comment]
Hi all,
I'm Bradley from Toronto, Canada.  I am an ALM student - digital media, and just finished my programming certificate (literally in the mail).  I'm a course assistant for CS50 and planning on going to Cambridge for summer school.  
I took E2 PHP last term and looking forward to this course. 
PHP/Laravel and Vue are my primary coding language at work where I create data analytics software.  I'm a self-taught programmer from before the days of frameworks so frameworks don't come natural.  Looking to learn the proper way of doing things.

**Comment by andlearnmore** [comment]
Hi All, 

I'm Anne, from Boston, MA. I also took E2 last semester and am excited to see some familiar names here and to launch into this course. I'm trying to decide whether I'm pursuing a Programming certificate (my original idea) or the Back-End certificate. 

I've always worked in higher education administration (including at Wellesley, @susanBuck!)--essentially doing nothing related to coding--but am finding myself loving the coding courses I've taken at HES. 

Looking forward to the semester with everyone!

**Comment by ghost** [comment]
Hi All,

My name is Jackson. My background is in Java. I enjoy coding part-time. I am relatively new to Laravel Framework. I have already completed DGMD E-2 and hope to enjoy this course.

**Comment by dannybodner21** [comment]
Hi All,

My name is Danny. I am from Cleveland, Ohio, but I am currently living in Okinawa, Japan.

I have a good amount of programming experience, but I am new to PHP/Laravel. The reason I chose this course specifically is because my brother has a website built using the Laravel Framework that he would like me to help him with. I figured this course was a great place to start.

Very excited to get started!

**Comment by traveler9878** [comment]
Hi I'm David Curtis.  I'm trying to graduate with the ALM this May and I need one elective and my capstone.  I selected this course because I took the E2 course last fall and was very impressed with the quality of the training and support.  The E2 course was probably the best programming oriented course I've ever experienced.

**Comment by susanBuck** [comment]
So good to see so many returning students! 

@ROK862 Can't wait to hear your impressions of Laravel at the end of the semester. :-)
