### ISSUE TITLE
Week 6 - Sharing Data With All Views

### ISSUE THREAD

**Issue by bar181** [susanBuck/e15-spring23#11]
Purpose: I want a way to have common variables available within all pages of my views for a user.  For example, "Location" for a bookmarks page.  

From readings: [Creating & Rendering views](https://laravel.com/docs/views#creating-and-rendering-views)  

Approach: Set up a new middleware

My thoughts: I haven't done this before so thought it was worth a try. I little more involved that I expected when I first started.  

Here is help source: [https://laravel.com/docs/10.x/middleware#main-content](https://laravel.com/docs/10.x/middleware#main-content)
My github for bookmark: [https://github.com/bar181/e15/tree/main/bookmark](https://github.com/bar181/e15/tree/main/bookmark)
My URL: [http://bookmark.bradross.me/tests](http://bookmark.bradross.me/tests) (this is my testing page so there is no navbar)

STEPS
1) php artisan make:middleware ShareLocationData
- new file in Http/Middleware

2) file: Http/Middleware/ShareLocationData 
-> go to: public function handle(Request $request, Closure $next)
-> add before the return: session()->put('location', 'Toronto, Canada');

3) file: Http/Kernel
-> go to: protected $routeMiddleware
-> add at end of list: 'share.location' => \App\Http\Middleware\ShareLocationData::class,

4) file: web
-> add middleware to end of your route(s)
-> example: Route::get('/tests', [PageController::class, 'tests'])->middleware('share.location');

5) file: Http/Controller/PageController
-> get value in your function and add it to your return
example: $location = session('location', 'Default Value');
        return view('pages/tests', ['location' => $location]);

6) Use in your blade tests.blade.php
example: <p>Shared location: {{ $location }}</p>

7) Results on tests.blade.php
Shared location: Toronto, Canada 

8) Future use case
Adjust step 2 (hard coded value) to a query for a specific user

**Comment by andlearnmore** [comment]
I'm so glad to see you did this--this was the other thing I was considering exploring! What I was puzzling over is when we might want to have common variables available across all views. This location use makes sense. 

Would the alternative to doing it this way be to put a small function in the main template that would return the location? (I did something like this with the date function in main.blade.php in my [Bookmark](http://bookmark.andlearn.me/) app):  

`<section> It's day {{ date('z') }} of {{ date('Y') }}. How many books have you read this year? </section>`

If this were a more complex app with logins and user profiles, would that be another time to use this approach of having access to common variables across all views--such that each page would have access to a logged-in user's profile details? Or does Laravel account for these profile details in other ways?

(This is one thing I wish documentation would include more of--potential use cases. When it says, "you may" do something some way, I wish it would elaborate to say under what conditions you might want to do that thing, or what benefit it offers over doing something another way. As someone new to coding, it would be helpful to know _why_ I'd do something; just knowing _that I can_ feels like too much information in the absence of that understanding.)

**Comment by bar181** [comment]
For me, the use case was to provide access about a user that isn't available in a users table.  For example, I am creating a new app with an AI assistant that helps a user throughout the website.  All pages can get access to the user's details from the users table but these sets of variables were in a different tables and I needed to query and pass the variables in every controller.  Similar to your example of having a phone number accessible on all pages.  

After trying the new middleware, I can see applications where certain pages have shared middleware.  Right now it isn't needed for me personally but I am glad I know how in case things change. 

I can see the main way of using new middleware is for user permissions to determine what a user can do/not-do
