### ISSUE TITLE
Livewire

### ISSUE THREAD

**Issue by lmarshman** [susanBuck/e15-spring23#12]
Going through the readings this week, one thing that caught my eye was Livewire. In the past I've found it challenging to move to the front-end and incorporate JavaScript into my aps, so something that would spare me having to do that  seems like a godsend. I went through the [Quickstart](https://laravel-livewire.com/docs/2.x/quickstart) section on Livewire's website to get a better sense of it and added a basic "book" counter to my bookmark application.

To add the counter to my page, I created a component using the `php artisan make:livewire counter` command. It created two folders: 1 in Http (called livewire) and one in my views (also called livewire). The counter came with boilerplate code for the controller file and the views, which you can view [here](https://github.com/lmarshman/e15/blob/01386cf99b269d1e46120ae30ba91674bbd00852/bookmark/app/Http/Livewire/Counter.php) and [here](https://github.com/lmarshman/e15/blob/main/bookmark/resources/views/livewire/counter.blade.php), respectively.

To render livewire on your page, you simply have to include the following three lines of code in the view you want it displayed on:
- @livewireStyles
- @livewireScripts
- <livewire:counter />

I chose to display them on my bookmark welcome page:

```
`@extends('layouts/main')

@section('content')
    @livewireStyles
    @livewireScripts
    <p>How many books would you like to read this year?</p>
    <livewire:counter />
    <p>Welcome to Bookmark. Please check back later.</p>
@endsection`
```

While the counter isn't particularly impressive, in reading through more of the Livewire doc, the counter only scratches the surface. Down the road when we create more dynamic applications, I imagine that the [Actions](https://laravel-livewire.com/docs/2.x/actions) and [Events](https://laravel-livewire.com/docs/2.x/events) pages could be very useful.

**Comment by susanBuck** [comment]
@lmarshman - Glad you got to explore Livewire, and thanks for sharing your example. It is a neat tool for those who don't want to context switch between front-end and back-end code!

**Comment by dannybodner21** [comment]
I also read a bit on Livewire. It seems extremely useful for more complex applications we're going to build in upcoming projects.

**Comment by bar181** [comment]
Thanks for the share.  Cool tool !
