### ISSUE TITLE
Week 6 - User Authentication

### ISSUE THREAD

**Issue by dannybodner21** [susanBuck/e15-spring23#13]
Something that stuck out to me while going through this weeks readings was the block on authentication. When building an application, giving your user the ability to register, login and logout is extremely important to having a tailored and secure website experience, so I decided to read more about it.

Our reading had a section on authentication directives, which showed that you can very easily check if the current user is authenticated or not, and display custom data, by using ```@auth/@endauth``` or ```@guest/@endguest``` tags.

I tested this in our bookmark application with the following code:
```html
@auth

<p>You are currently an authenticated user.</p>

@endauth

@guest

<p>You are not logged in. Please login <a  href='/'>here</a>.</p>

@endguest
```

Although this is a very simplistic test, it does show what we would expect for an unauthorized user. However, I can’t yet test if the auth tag works as expected because there is nothing set in place to allow a user to register and login in on this application.

I decided to read a little further on how we might allow user registration in the future and came across one of the starter kits that Laravel provides, called Breeze. Breeze integrates with your Laravel application to help you with allowing a user to authenticate him/herself by providing you with routes, controllers and views that you would need to register, login and logout your users.

You can read more about Laravel Breeze [here](https://laravel.com/docs/10.x/starter-kits).

And you can view my very simple test of an unauthenticated user [here](https://github.com/dannybodner21/e15/blob/main/bookmark/resources/views/layouts/main.blade.php).

**Comment by susanBuck** [comment]
Great write-up, thanks @dannybodner21. FYI We'll talk about authentication in Week 11.
