### ISSUE TITLE
Passing Data on All Views with share()

### ISSUE THREAD

**Issue by coeure-d-elephante** [susanBuck/e15-spring23#14]
In order to share data with all views, we can use the view facade's share() method.
This feature can be useful to a project like Book

mark to share data such as $title where this information can be needed in all the pages. 

I haven't yet figured out how exactly this method is going to be implemented in my project but I'm currently working on it. 

What I do understand is within this function we need to replace
'key' = 'title'
'value' = for the path to get the value of each title. Such as $title.id(?)

public function boot(): void
    {
        View::share('key', 'value');
    }

Reference: (https://laravel.com/docs/10.x/views#sharing-data-with-all-views)

I've also utilised this YT video: https://youtu.be/HWKX48j6ywk

Below I've provided 2 examples of how I've attempted to implement this method in my Bookmark project.

<img width="1010" alt="Screenshot 2023-03-07 at 13 42 10" src="https://user-images.githubusercontent.com/78046295/223559495-6ffe1f43-01d1-486b-b5cc-6473b575aca5.png">
<img width="737" alt="Screenshot 2023-03-07 at 13 59 15" src="https://user-images.githubusercontent.com/78046295/223562967-85e690fd-ef41-44b7-8e54-7ab9ec267864.png">

**Comment by bar181** [comment]
Thanks.  I'll check it out.  This looks perfect.  I was looking for something that didn't require code for each route.
