### ISSUE TITLE
Prevention of escaped characters

### ISSUE THREAD

**Issue by sicwere** [susanBuck/e15-spring23#15]
By default, Blade's echo syntax escapes special characters to prevent XSS attacks. One way to prevent this behavior is to enclose a variable containing special characters with the syntax {!! !!}. On my bookmark site, I created the following variable:
```php
$ampersand = '&amp;'
```
I then added the following HTML code to the Bookmark welcome page:
```html
<body>
    <h1>Bookmark</h1>

    <p>Here is the ampersand variable escaped: {{ $ampersand }}</p>

    <p>And here it is not escaped: {!! $ampersand !!}</p>
</body>
```

Here are the results:
![image](https://user-images.githubusercontent.com/11153087/223603389-4acd1154-c477-4d9c-8ef8-9f1ab2026655.png)

Alternately, you can add the line  ```Blade::withoutDoubleEncoding``` to the ```boot``` method of the ```AppserviceProvider```. This would disable escaping throughout the entire Laravel app:
```php
<?php
 
namespace App\Providers;
 
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;
 
class AppServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Blade::withoutDoubleEncoding();
    }
}
```
One reason you may want to do this is to display how escaping works, as can be seen in the **Performed translations** table on the _htmlspecialchars_ page in the PHP manual: [htmlspecialchars](https://www.php.net/manual/en/function.htmlspecialchars.php)

**Comment by susanBuck** [comment]
Good write-up and great use case example, @sicwere.
