### ISSUE TITLE
Undefined variable $searchTerms

### ISSUE THREAD

**Issue by lmarshman** [susanBuck/e15-spring23#17]
I'm following along with video Part 2 and have run into an error that I can't figure out. I am currently at the part of the video where we are trying to output the $searchTerms to the page, but I keep getting an undefined varialbe for $searchTerms. I've rewatched this part of the video several times and cannot spot my error. As in the video, I'ved updated my [BookController](bookmark/app/Http/Controllers/BookController.php) as so:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Arr;

class BookController extends Controller
{

    /**
     * GET/search
     * Searches books based on title or author
     */
    public function search(Request $request)
    {

        $bookData = file_get_contents(database_path('books.json'));
        $books = json_decode($bookData, true);

        $searchTerms = $request->input('searchTerms', null);
        $searchType = $request->input('searchType', null);

        
        $searchResults = [];

        foreach($books as $slug=>$book) {
            if(strtolower($book[$searchType] == $searchTerms)) {
                $searchResults[$slug] = $book;
            }
        }

        return redirect('/')->with([
            'searchTerms' => $searchTerms,
            'searchType' => $searchType,
            'searchResults' => $searchResults
        ]);
    }
```

I've also updated my [PageController](https://github.com/lmarshman/e15/blob/main/bookmark/app/Http/Controllers/PageController.php) according to the video:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PageController extends Controller
{
    public function index()
    {
        $searchResults = session('searchResults', null);
        $searchTerms = session('searchTerms', null);
        $searchType = session('searchType', null);

        return view('pages/welcome',[
            'searchResults' => $searchResults,
            'searchTerms' => $searchTerms,
            'searchType' => $searchType,
        ]);
    }
    
    public function welcome()
    {

        $searchResults = session('searchResults', null);
        return view('pages/welcome', ['searchResults' => $searchResults]);
    }

    public function contact()
    {
        return view('pages/contact');
    }
}
```

And finally, I've attempted to add $searchTerms to my [welcome.blade.php](https://github.com/lmarshman/e15/blob/main/bookmark/resources/views/pages/welcome.blade.php) file using the "{{ }}" notation, but continue to get an error saying the term is undefined. I assume the issue must be in one of my controller files but I can't spot the error. A fresh pair of eyes would be much appreciated. Thank you!

**Comment by susanBuck** [comment]
@lmarshman - I just cloned a copy of your repository to test things out and was unable to recreate the issue on my end. Demo here: http://lmarshman.hesweb.xyz 

I'm wondering if you perhaps spotted/fixed the issue already as I'm a bit delayed in responding to this? :-) 

If you're still experiencing the issue on your end, let me know!

**Comment by susanBuck** [comment]
Closing this thread since I spoke with @lmarshman off thread and determined the issue was all sorted out. 👍
