### ISSUE TITLE
P2 success results?

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e15-spring23#19]
I think I have P2 mostly done, I'm going to a success page that validates and dumps the request variables to the page on success.

I'm not attempting to reload the page with form data on a refresh click or anything like that.

On validation failure I'm returning to the form and populating with the old data.

Just looking to confirm that this meets the goals for P2.

**Comment by susanBuck** [comment]
Hi @traveler9878 - The success page should do more than just dump the form data to the page. It should do some processing with that data and output some results. 

See the demos and wireframes on the project specs for examples: https://hesweb.dev/e15/projects/2

**Comment by traveler9878** [comment]
Ok thanks, getting something working on that now...
