### ISSUE TITLE
Using p2 as a base for p3?

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e15-spring23#22]
I'm planning to start p3 from where I left of with p2.  I started by doing a copy and past in VSCode of the p2 directory into a p3 directory.  I know I will need to setup the web server to recognize p3 and a few other things but I'm wondering if this is an 'ok' thing to do in the laravel environment or if laravel needs to actually create the project due to underlying configurations or something like that...  also thought this would make an interesting post for the class collaborations.

Thanks.

**Comment by susanBuck** [comment]
Hi @traveler9878 - Good question. It is possible to duplicate an existing Laravel project, but there are some steps you'll need to take to get it operational. 

For insight into this, check out the Part 6 of this week's videos where I talk about setting up a production version of an application, as it's very similar to what you're trying to do. The difference is, you won't be cloning the repository to get the copy - instead you'll just duplicate the p2 folder. There are a few other small differences as well so here's a summary of the steps:

+ Duplicate and rename project directory
+ Remove `vendor` directory and rebuild with `composer update`
+ Run commands to set appropriate permissions on `storage` and `bootstrap/cache`
+ Set up .env file
+ Run `php artisan key:generate` to generate application key
+ Edit nginx sites config, adding a new config for the new application

If you run into any road blocks getting it up and running, let me know.

**Comment by traveler9878** [comment]
great, thanks that's the way i'll plan to go then
