### ISSUE TITLE
Project planning tips?

### ISSUE THREAD

**Issue by andlearnmore** [susanBuck/e15-spring23#23]
Hi everyone! A lot of you have more experience in this field than I and so I'm hoping you can give me some advice on how you approach projects. 

What are some tools, applications, strategies you use when designing a project? How, when you're in the design stage, do you keep track of the different things you want your app to be able to do, the views you want it to have, how you want it to all be laid out?

I'm not a great planner and tend to jump in and things end up less organized than I'd like--or I spend a lot of time trying to go back and put some sort of order to the original disorder I've created!! 

Thanks!
-Anne

**Comment by lmarshman** [comment]
This really is a great question! I'm also interested in the organizational process of more experienced programmers. Something that helps me to be organized is to set up all my views first. It's helpful to me to get the overall look of the website and pages before starting on the features. This way, when I start implementing my features, they either appear as I expect them to, or not and I have to debug my controllers/routes/etc. How do you typically get started on projects?

**Comment by traveler9878** [comment]
The iterative approach where you build something that works and then do follow on iterations to add functionality prevents you from "biting off more than you can chew", in my humble opinion (IMHO)...

**Comment by susanBuck** [comment]
I don't use any special tools - just a text editor and a to-do list. I start with big "to-dos" and then break each one down as much as possible. If I have too broad of a "to-do" on a list, I tend to avoid it, so I try to come up with very specific actionable steps.

When it comes to code, I do something similar to what @traveler9878 described. I try and get a rough/basic prototype working, then I iterate on that.

I tend to approach both code/design at the same time, bouncing back and forth between the two. 

To me the process ends up feeling very much like a sculpture where you're just chiseling away a little at a time until you get the end results you want.

**Comment by andlearnmore** [comment]
Thank you! It's helpful to hear these approaches.
