### ISSUE TITLE
phpMyAdmin Not Installing correctly

### ISSUE THREAD

**Issue by lmarshman** [susanBuck/e15-spring23#24]
I'm working on installng phpMyAdmin and am running into an error when trying to make the connection between my server and the phpMyAdmin files. I followed the steps outlined in the vidoe/notes however, when I run the `sudo ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin` command, I receive an errorr saying that there is no file or director by the name of '/var/www/html/phpmyadmin'. 

I uninstalled/reinstalled phpMyAdmin again to double-check I followed the steps correctly, and as far as I can tell, I have. I've included the readouts from my terminal showing the error message I'm getting. I'm not sure why the phpMyAdmin folder isn't being created.

`root@HES:/var/www/e15# sudo apt install phpmyadmin`
`Reading package lists... Done`
`Building dependency tree... Done`
`Reading state information... Done`
`phpmyadmin is already the newest version (4:5.1.1+dfsg1-5ubuntu1).`
`0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.`
`root@HES:/var/www/e15# sudo ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin`
`ln: failed to create symbolic link '/var/www/html/phpmyadmin': No such file or directory`

**Comment by susanBuck** [comment]
Hi @lmarshman -

I checked on your server and see you don't have a `/var/www/html` directory anymore. This was a default web directory that was initially set up on our servers. It's possible you cleaned it up at some point since we hadn't been using it?

To address this, you can recreate the directory in question:

```bash
> mkdir /var/www/html
```

Then try the symbolic link command again. If that doesn't work, let me know!

**Comment by lmarshman** [comment]
Oh! Yes you're right that was the issue. I didn't realize it's importance and thought it was just an extranious folder. And then forgot I had deleted it when going thorugh the steps. Thank you!

**Comment by susanBuck** [comment]
Np, glad it was a quick fix! : )
