### ISSUE TITLE
Error with the books table seeder - "Field 'author' doesn't have a default value"

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e15-spring23#26]
Database\Seeders\BooksTableSeeder ........................................................................................................ RUNNING  

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 1364 Field 'author' doesn't have a default value (SQL: insert into `books` (`created_at`, `updated_at`, `slug`, `title`, `author_id`, `published_year`, `cover_url`, `info_url`, `purchase_url`, `description`) values (2023-04-16 19:39:35, 2023-04-16 19:39:35, the-great-gatsby, The Great Gatsby, 1, 1925, https://hes-bookmark.s3.amazonaws.com/the-great-gatsby.jpg, https://en.wikipedia.org/wiki/The_Great_Gatsby, http://www.barnesandnoble.com/w/the-great-gatsby-francis-scott-fitzgerald/1116668135?ean=9780743273565, The Great Gatsby is a 1925 novel written by American author F. Scott Fitzgerald that follows a cast of characters living in the fictional towns of West Egg and East Egg on prosperous Long Island in the summer of 1922. The story primarily concerns the young and mysterious millionaire Jay Gatsby and his quixotic passion and obsession with the beautiful former debutante Daisy Buchanan. Considered to be Fitzgerald’s magnum opus, The Great Gatsby explores themes of decadence, idealism, resistance to change, social upheaval and excess, creating a portrait of the Roaring Twenties that has been described as a cautionary tale regarding the American Dream.))

**Comment by traveler9878** [comment]
Removed authors from the Books table in BooksTableSeeder.  Works now.

**Comment by traveler9878** [comment]
Actually it's the create_books_table migration up code that I modified:

    public function up()
    {
        Schema::create('books', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->string('slug');
            $table->string('title');
            //$table->string('author');
            $table->smallInteger('published_year');
            $table->string('cover_url');
            $table->string('info_url');
            $table->string('purchase_url');
            $table->text('description');
        });
    }

**Comment by susanBuck** [comment]
Hi @traveler9878 -

It's true that with the addition of the author one-to-many relationship, how we previously handled authors (directly embedded in the books table) needs to be amended in the migrations and seeds.

For the migration, the `author` field is removed and replaced with `author_id`. In the notes this is done via the`connect_authors_and_books` migration ([ref](https://hesweb.dev/e15/notes/laravel/db-one-to-many#connect-authors-and-books-tables)):

```php
# Remove the field associated with the old way we were storing authors
# Can do this here, or update the original migration that creates the `books` table
# $table->dropColumn('author');
```

...but it could also be accomplished by editing the original books table migration as you've done. That's how I did it in the lecture video (see [Week 11, Part 4](https://www.youtube.com/embed/mpoPc399yWU?rel=0&showinfo=0)  starting at the 15:00 mark).

And the change to the seeder is described in the notes [here](https://hesweb.dev/e15/notes/laravel/db-one-to-many#update-the-books-table-seeder) and covered in the [Week 11, Part 4](https://www.youtube.com/embed/mpoPc399yWU?rel=0&showinfo=0) video at around the ~16:00 mark.

**Comment by susanBuck** [comment]
I believe this issue is resolved so I'm going to close it out, but don't hesitate to re-open or start a new thread if there are any pending questions.
