### ISSUE TITLE
Issues connecting to the server

### ISSUE THREAD

**Issue by lmarshman** [susanBuck/e15-spring23#3]
Hello,

I am working through video 3 - Remote Development, and am encountering issues connecting to the servier. I have followed the steps outlined in the video to install/setup the remote development extension and configuring my connection. When I attempt to connect, a new VSCode window appears and attempts to connect to the host, but ultimatley is not able to.

I've included several screenshots of the windows I encounter. The first is showing my config file with the host name updated to my IP address. I've saved the file several times to make sure that isn't the issue. The second screenshot is simply showing the new window that initially pops up when I attempt to connect to the host. The third screenshot is the error messages that occur when choosing windows as the platform of the remote host. I'm not sure if it's necessary to choose a platform, but when I do, this is when I finally get a response from the window that the attempt to connect has failed. I've retraced my steps, but am encountering the same result each time.

I'm not sure why the connection is failing. If anyone has ideas, I would really appreciate it!

![Screenshot of terminal and config file](https://user-images.githubusercontent.com/78757942/216501452-f9d59f71-71b0-4945-960c-5d1ceb5734c2.PNG)

![Opening remote stuck](https://user-images.githubusercontent.com/78757942/216501470-8150bc68-b73f-4405-9bbb-0293e50f5e48.PNG)

![retry loading window](https://user-images.githubusercontent.com/78757942/216501483-c15c5a2b-ab24-4ea0-916a-20c2b8839f61.PNG)

**Comment by susanBuck** [comment]
I was able to connect to your server from my VSCode on my Mac - booting up my Windows system now to test there. Will report back shortly with more info!

**Comment by susanBuck** [comment]
Hi @lmarshman -

Re-reading through your post, this line stood out at me:

> The third screenshot is the error messages that occur when choosing windows as the platform of the remote host.

The platform of the remote host is actually Linux. You're connecting from a Windows computer, but our servers are running Linux.

Try choosing Linux next time and let me know if that fixes things.

**Comment by lmarshman** [comment]
Hi @susanBuck ,

Ah thank you! That was the issue. Everything worked fine after that.

**Comment by susanBuck** [comment]
@lmarshman - Glad to hear it!
