### ISSUE TITLE
Routing Error for deleting books from user list

### ISSUE THREAD

**Issue by lmarshman** [susanBuck/e15-spring23#30]
I'm working on the practice feature in the Bookmark application to delete a book from a user list, and am running into what I assume is a routing error, but am not sure. When I attempt to click on the delete link in the list, I receive an error that says "The GET method is not supported for route list/removeBook. Supported methods: DELETE."

I've researched the issue and the general concensus seems to be that this error happens when a person forgets to include `{{ method_field('delete') }}` in their form. However, I do have this in my form. Here are the different relevant pieces of my code:

`Route::get('/list/{slug}/delete', [ListController::class, 'delete']);`
`Route::delete('/list/{slug}', [ListController::class, 'destroy']);`

The href for the remove from list button:

`<a href='/list/{{ $book->slug }}/delete'><i class='fa fa-minus-circle'></i> Remove from your list</a>`

My form in the removeBook blade (the purpose of the blade is to verify that a user wants to delete the book from their list):

```
    <form method='POST' action='/list/{{ $book->slug }}'>
        {{ method_field('delete') }}
        {{ csrf_field() }}
        <button type='submit' class='btn btn-danger'>Delete {{ $book->title }}</button>
    </form>
```
And my ListController Functions:

```
public function delete($slug)
    {
        $book = Book::findBySlug($slug);

        if (!$book) {
            return redirect('/list')->with([
                'flash-alert' => 'Book not found'
            ]);
        }

        return view('/list/removeBook', ['book' => $book]);
    }

    public function destroy($slug)
    {
        $user = $request->user();
        $book = Book::findBySlug($slug);

        $book->users()->detach();

        $book->delete();

        return redirect('/list')->with([
            'flash-alert' => '“' . $book->title . '” was removed from your list.'
        ]);
    }
```

I think I've been staring at the problem for so long that I can't see the error. If anyone has run into this before, or can spot the error,  I would really appreciate the insight.

**Comment by susanBuck** [comment]
Hi @lmarshman - Looking at the code you've provided, nothing obvious stands out to me as wrong. I tested it out on http://bookmark.lauramarshman.com and it appeared to work successfully.

Any chance you got the issue resolved between making this post and now? : )

**Comment by lmarshman** [comment]
This is really strange. I very specifically stopped working on this feature because I was feeling like I hit a wall, and moved on to the testing. But you're right, now that I've gone back to it, it does seem to be working. The only thing I can think of is that when I worked with Django, sometimes you had to do a hard reload of the browser for everthing to update properly. I thought I had done that, but perhaps not. Regardless, I'm glad it's resolved! Thank you!
