### ISSUE TITLE
Codeception bootstrap errors, didn't install acceptance

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e15-spring23#39]
ot@hes:/var/www/e15/p3/tests/codeception# codecept generate:cest acceptance LoginPage

In Configuration.php line 341:
                                   
  Suite acceptance was not loaded  
                                   

generate:cest <suite> <class>

root@hes:/var/www/e15/p3/tests/codeception# cd ../..
root@hes:/var/www/e15/p3# codecept bootstrap tests/codeception

==== Redirecting to Composer-installed version in vendor/codeception. You can skip this using --no-redirect ====

In InitTemplate.php line 201:
                                                      
  Codeception is already installed in this directory  
                                                      

bootstrap [-s|--namespace [NAMESPACE]] [-a|--actor [ACTOR]] [-e|--empty] [--] [<path>]

root@hes:/var/www/e15/p3#

**Comment by traveler9878** [comment]
I fixed it.  It said it couldn't find composer.json and installed itself without the acceptance and phpbrowser requirements to composer.json so it seems to have also not installed the acceptance module.  I added phpbrowser manually, acceptance was already there to composer.json and ran composer update.  it ran successfully.  I removed the codeception folder using vscode and ran codecept bootrap again and it worked:

 Codeception is installed for acceptance, functional, and unit testing 

Next steps:
1. Edit tests/acceptance.suite.yml to set url of your application. Change PhpBrowser to WebDriver to enable browser testing
2. Edit tests/functional.suite.yml to enable a framework module. Remove this file if you don't use a framework
3. Create your first acceptance tests using codecept g:cest acceptance First
4. Write first test in tests/acceptance/FirstCest.php
5. Run tests using: codecept run

**Comment by traveler9878** [comment]
still having p3 codecept issues:

root@hes:/var/www/e15/p3# php vendor/bin/codecept generate:cest acceptance LoginPage

In Configuration.php line 181:
                                              
  Configuration file could not be found.      
  Run `bootstrap` to initialize Codeception.  
                                              

generate:cest <suite> <class>

root@hes:/var/www/e15/p3#

**Comment by traveler9878** [comment]
first attempt using command line from notes:

root@hes:/var/www/e15/p3# codecept generate:cest acceptance LoginPage

==== Redirecting to Composer-installed version in vendor/codeception. You can skip this using --no-redirect ====

In Configuration.php line 181:
                                              
  Configuration file could not be found.      
  Run `bootstrap` to initialize Codeception.  
                                              

generate:cest <suite> <class>

root@hes:/var/www/e15/p3#

**Comment by traveler9878** [comment]
I'm going to try removing it and installing it again.

**Comment by traveler9878** [comment]
ah... running from p3.. wrong directory...

**Comment by traveler9878** [comment]
Didn't fix it:

oot@hes:/var/www/e15/p3/tests/codeception# codecept generate:cest acceptance LoginPage

In Configuration.php line 341:
                                   
  Suite acceptance was not loaded  
                                   

generate:cest <suite> <class>

root@hes:/var/www/e15/p3/tests/codeception#

**Comment by traveler9878** [comment]
found the issue:  codeception has changed the a in acceptance to A in Acceptance:

root@hes:/var/www/e15/p3/tests/codeception# codecept generate:cest Acceptance LoginPage
Test was created in /var/www/e15/p3/tests/codeception/tests/Acceptance/LoginPageCest.php
root@hes:/var/www/e15/p3/tests/codeception#

**Comment by traveler9878** [comment]
I guess it's progress...:
root@hes:/var/www/e15/p3/tests/codeception# codecept generate:cest Acceptance LoginPage
Test was created in /var/www/e15/p3/tests/codeception/tests/Acceptance/LoginPageCest.php
root@hes:/var/www/e15/p3/tests/codeception# codecept run acceptance --steps
Codeception PHP Testing Framework v4.2.2 https://helpukrainewin.org
Powered by PHPUnit 8.5.28 #StandWithUkraine

In Run.php line 464:
                                         
  Suite 'acceptance' could not be found  
                                         

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]

root@hes:/var/www/e15/p3/tests/codeception# codecept run Acceptance --steps
Codeception PHP Testing Framework v4.2.2 https://helpukrainewin.org
Powered by PHPUnit 8.5.28 #StandWithUkraine

In ModuleContainer.php line 117:
                                                           
  Module \Helper\Acceptance could not be found and loaded  
                                                           

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]

root@hes:/var/www/e15/p3/tests/codeception#

**Comment by traveler9878** [comment]
I'm going to continue with coding the tests even though I can't run them currently, looks like at least I can create the test classes.

**Comment by susanBuck** [comment]
If it's okay, going to log into your server now to take a look.

**Comment by traveler9878** [comment]
Thanks, I just saw the root update and restarted again and i'm still
getting the same codeception error not finding the Helper

**Comment by traveler9878** [comment]
I'm not sure but when I started digging into it I was seeing case
mismatches between the namespaces and the directories, test vs Test was one
case

**Comment by traveler9878** [comment]
Thanks I’m definitely done for the day…

**Comment by susanBuck** [comment]
**Here's the notes on what I found/did:**

Confirmed Codeception would not run as expected, couldn't quite pinpoint why. Decided best course of action was to try a fresh setup following these steps:

**Removal:**
+ Backed up test files (contents of `tests/codeception/tests/acceptance`)
+ Deleted `/tests/codeception` directory.
+ Removed both codeception-related dependencies (module-asserts and phpbrowser) from composer.json
+ Run `composer update`

**Reinstallation** (following the [steps in the notes](https://hesweb.dev/e15/notes/laravel/testing-codeception#project-setup)):
+ Ran `codecept bootstrap tests/codeception` from within `p3/`
+ Ran `composer require "codeception/module-asserts" --dev`
+ Updated `tests/codeception/tests/acceptance.suite.yml` as appropriate

**Seeing if it worked...**
From within `tests/codeception` ran `codecept run acceptance` just to see if the tests system would run:

```
Codeception PHP Testing Framework v4.2.2 https://helpukrainewin.org
Powered by PHPUnit 8.5.28 #StandWithUkraine

Acceptance Tests (0) ----------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------
No tests executed!
```

After confirming it would run, restored backed up test files. Ran Acceptance tests again (`codecept run acceptance`) and they were all failing with this error:

```
[InjectionException] Failed to inject dependencies in instance of 'Tests\CreatePageCest'. Class "Tests\AcceptanceTester" does not exist  
```


Looked at tests files and saw they had the following namespace and use statements at the top, which were not present in the Bookmark examples.

```
namespace Tests;
use Tests\AcceptanceTester;
```

Removed those lines and ran tests again (`codecept run acceptance`) and all the test files were passing except `LoginPageCest`:

```
1) LoginPageCest: User can log in
 Test  tests/acceptance/LoginPageCest.php:userCanLogIn
 Step  See "Logout","nav"
 Fail  Element located either by name, CSS or XPath element with 'nav' was not found.
```

This is failing because there is no nav element on the page. To address I added a "test" attribute to the logout link:

```html
<a id='navlink' href='#' test='logout-link' onClick='document.getElementById("logout").submit();'>Logout</a>
```

And updated the test to search for that:
```php
$I->seeElement('[test="logout-link"]');
```


With that, all tests were now passing. 🙂 
```
root@hes:/var/www/e15/p3/tests/codeception# codecept run acceptance 
Codeception PHP Testing Framework v4.2.2 https://helpukrainewin.org
Powered by PHPUnit 8.5.28 #StandWithUkraine

Acceptance Tests (5) ----------------------------------------------------------------------------------------
✔ CreatePageCest: Try to test (0.00s)
✔ HideNoteCest: Try to test (0.00s)
✔ ListPageCest: Try to test (0.00s)
✔ LoginPageCest: User can log in (1.48s)
✔ RgisterPageCest: Try to test (0.00s)
-------------------------------------------------------------------------------------------------------------


Time: 2.4 seconds, Memory: 18.66 MB

OK (5 tests, 4 assertions)
```

If any other weirdness pops up, let me know!

**Comment by traveler9878** [comment]
Thanks!
