### ISSUE TITLE
Palindrome question

### ISSUE THREAD

**Issue by sicwere** [susanBuck/e15-spring23#4]
For assignment 1, the instructions says that the palindrome processor should ignore special characters. But how should the processor handle strings that consist of only special characters?

**Comment by susanBuck** [comment]
Hi @sicwere - Good question! 

Given the specification of _Non-alphabetic characters are ignored_, I think the way we should handle this is it should yield "No".

That being said, [my demo](https://e15p1.hesweb.dev) was failing to do that. :-) I just corrected it to handle the edge case of an empty string (which is what you're left with if you strip out all special characters from a string of just special characters).

I've also updated the p1 specs to address this:

```
Is palindrome?
Indicates whether the input string is an alphabetic palindrome (letters same forwards and backwards). Case insensitive. Non-alphabetic characters are ignored.

Example strings and results:

"racecar" => Yes
"Racecar" => Yes
"racecar!" => Yes
"!racecar!" => Yes
"Hello World" => No
"!!" => No
"!@#$" => No
```

Thanks for bringing this up - always good to think of all those edge cases.
