### ISSUE TITLE
login.blade.php and register.blade.php not rendering properly despite installing Fortify

### ISSUE THREAD

**Issue by coeure-d-elephante** [susanBuck/e15-spring23#40]
Hi,

I can verify that I've followed these steps from the lecture onto my P3 and yet the auth/login and auth/register aren't rendering well due to permission issues.

https://hesweb.dev/e15/notes/laravel/auth-setup

https://flareapp.io/share/lm2DW4D7

Please help. Thank you!

**Comment by susanBuck** [comment]
The error of `The stream or file "/var/www/e15/p3/storage/logs/laravel.log"` sounds like a permission issue on the storage directory. Ref: [New Laravel App - Permissions](https://hesweb.loc/e15/notes/laravel/new-laravel-app#permissions).

I logged into your server to take a look. I could see that the storage directory had the correct owner of `www-data`, but digging into the directory I saw `/p3/storage/logs/laravel.log` was owned by `root`, not `www-data`.

To address, I ran `chown -R www-data storage`, and then was able to load the application (http://e15p3.ssjavier.world).

I’m not sure why just the laravel log within storage would have had its permissions altered, so if you see this happen again, let me know and we can dig deeper.
