### ISSUE TITLE
Unable to create new controller

### ISSUE THREAD

**Issue by lmarshman** [susanBuck/e15-spring23#41]
I attempted to make a new controller, because I felt my RoutesController was becoming cluttered. However, when I entered php artisan make:controller ListController I recieved an error saying "local.ERROR: Unable to detect application namespace". After researching the issue, it was suggested to do a composer diagnose. This doesn't reveal any issues. Everything seems to be ok. It also suggested running a composer update, but this lead to more issues. I'm now receiving the following error:

"Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255"

And now my project won't even load on my server. Has anyone else run into this issue?

**Comment by susanBuck** [comment]
Hi @lmarshman - Logging into your server now to take a look. Will reply with more details shortly.

**Comment by susanBuck** [comment]
Your application is running now. 

When I tried to run `composer update`, it was giving the following error:

```
 Uncaught ReflectionException: Class "App\Console\Kernel" does not exist in /var/www/e15/p3/vendor/laravel/framework/src/Illuminate/Container/Container.php:914
```

I Googled the error and came across [this post](https://stackoverflow.com/questions/38918982/laravel-error-reflectionexception-class-app-http-kernel-does-not-exist). Some of the replies there were suggesting checking the psr-4 settings in the `composer.json` file, which is part of the configs for your application’s namespacing. This lines up with the error you were receiving about namespacing.

Looking at the psr-4 settings it looked like this:

```
"autoload": {
        "psr-4": {
            "App\\": "app/src",
```

It should look like this (remove `src`):

```
"autoload": {
        "psr-4": {
            "App\\": "app",
```

It looks like that "bug" was introduced in a commit made yesterday ([ref](https://github.com/lmarshman/e15/commit/d1501897fe1b74f748a13817c8ed5091d1ba5477#diff-0edef3c40c12f9a02e543ba65edb9320c06c3df9d795329d6e4a11457377bd5c)). 

You should be good to go now, but let me know if you come across any other hiccups.

**Comment by lmarshman** [comment]
Thank you so much! I'm not sure how I did that as I haven't touched that file. But I really appreciate your help! If I encounter the error again, I'll double-check that setting hasn't changed. Thank you again!
