### ISSUE TITLE
I'm not seeing the laravel section in the notes navigation?

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e15-spring23#5]
I must be missing something, I'm not seeing the laravel notes?

**Comment by traveler9878** [comment]
diregard, i see the notes now...

**Comment by susanBuck** [comment]
Ah yes, looks like I forgot to update the table of contents. I'll fix it when I get back to my computer. In the meantime you can follow the links from the weekly outline.

Thanks for the heads up.

**Comment by traveler9878** [comment]
Thank you

**Comment by susanBuck** [comment]
Fixed now.
