### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by sicwere** [susanBuck/e15-spring23#7]
I created my p2 folder at http://e15p2.sicwere.online/, but I'm getting a 403 error.

**Comment by susanBuck** [comment]
Hi @sicwere -

Can you run and share the output of the command `nginx -t` ? It will tell is if there are any issues in your sites configuration ([ref](https://hesweb.dev/e15/notes/infrastructure/subdomains)).

Please also share the contents of your sites config file (`/etc/nginx/sites-available/hes`) so that if the above command yields any issues, we can figure out why.

**Comment by sicwere** [comment]
nginx: [warn] server name "/var/www/e15/p2/public" has suspicious symbols in /etc/nginx/sites-enabled/hes:19
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

server {

listen 80;
server_name e15p1.sicwere.online;
root /var/www/e15/p1/;

index index.php index.html;

location ~ \.php$ {
fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
include fastcgi_params;
}
}
server {
listen 80;
listen [::]:80;
server_name bookmark.sicwere.online
root /var/www/e15/bookmark/public;

add_header X-Frame-Options "SAMEORIGIN";
add_header X-Content-Type-Options "nosniff";

index index.php;

charset utf-8;

location / {
try_files $uri $uri/ /index.php?$query_string;
}

location = /favicon.ico { access_log off; log_not_found off; }
location = /robots.txt { access_log off; log_not_found off; }

error_page 404 /index.php;

location ~ \.php$ {
fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
include fastcgi_params;
}

location ~ /\.(?!well-known).* {
deny all;
}
}
server {
listen 80;
listen [::]:80;
server_name e15p2.sicwere.online
root /var/www/e15/p2/public;

add_header X-Frame-Options "SAMEORIGIN";
add_header X-Content-Type-Options "nosniff";

index index.php;

charset utf-8;

location / {
try_files $uri $uri/ /index.php?$query_string;
}

location = /favicon.ico { access_log off; log_not_found off; }
location = /robots.txt { access_log off; log_not_found off; }

error_page 404 /index.php;

location ~ \.php$ {
fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
include fastcgi_params;
}

location ~ /\.(?!well-known).* {
deny all;
}
}

**Comment by susanBuck** [comment]
Looking near where it says the error is (line 19), I see that the previous line (18) is missing a semicolon at the end.

This:
```
server_name e15p2.sicwere.online
root /var/www/e15/p2/public;
```

Should be:
```
server_name e15p2.sicwere.online;
root /var/www/e15/p2/public;
```

Try fixing that, restarting your server (`systemctl restart nginx`), and seeing if the issue is resolved.

**Comment by sicwere** [comment]
Yes, it works now. Thank you.

**Comment by susanBuck** [comment]
Excellent, glad it's sorted out.
