### ISSUE TITLE
Assignment post - template inheritance

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e15-spring23#8]
This weeks assignment requires a post here regarding routes and views and readings.  I followed the material and created a template, used the template, created a view, and added a call to the view in the controller.

http://bookmark.davidcurtis.me/books/title
template:
<!doctype html>
<html lang='en'>

<head>
    <title>@yield('title')</title>
    <meta charset='utf-8'>
    <link href='/css/app.css' type='text/css' rel='stylesheet'>
    @yield('head');
</head>

<body>
    <header>
        <a href='/'><img src='/images/mye15logo.png' id='logo' alt='my E15 bookmark logo'></a>
    </header>

    <section>
        @yield('content');
    </section>

    <footer>
        &copy; My E15 bookmark footer
    </footer>

View:

@extends('layouts/main')

@section('title')
    {{ 'Hello Im the title' }}
@endsection

@section('head')
    {{ 'Im the head section' }}
@endsection

@section('content')
    {{ 'im the content' }}
@endsection

**Comment by traveler9878** [comment]
github link:  https://github.com/traveler9878/e15/tree/main/bookmark

**Comment by susanBuck** [comment]
Hi @traveler9878 - Thanks for being the first post on this topic. : )

Just to clarify I was hoping that in this prompt students would explore something they learned in the documentation that wasn't already covered in lecture. It's fine what you've shared but I just wanted to note it for other students who might be reading this thread.

A note on the code: in the instances where you're displaying just a string of text like `{{ 'Hello Im the title' }}` there's no need to use the Blade echo syntax. You can simply write `Hello Im the title`. The Blade echo syntax is only necessary if you have PHP expressions you're trying to echo out.

Let me know if you have any follow-up questions on that and thanks again for kicking off this exercise.

**Comment by traveler9878** [comment]
Thanks, I did get the intention here I am doing my capstone this term and I needed to get this knocked out to write user stories for the business case...
